[project]
name = "venture128"
version = "0.1.0"
description = "Custom Cipher Block Encryption for IF4020_Tugas2_2026_2027"
readme = "README.md"
authors = [
    { name = "19623248Git", email = "13523032@std.stei.itb.ac.id" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
venture128 = "venture128:main"
find_sbox_consts = "venture128.find_s_box.sboxfinder:find_consts"
generate_sbox = "venture128.find_s_box.sboxfinder:generate_s_box"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
